var scenarios = {

    1: "<i><p>'The Empire won't be able to take our colony', the First Founder said. 'If they try to, we can ultimately repel them with </i>it<i>.'</p> <p>'If we start a war, we will surely be destroyed', I argued. 'Wouldn't it be better to aim for a favorable peace treaty while we still have something to negotiate with?'</p><p>The First Founder looked at me with a condemning expression.</p><p>'If you pursue this issue, Faron, I'll ask for you to be removed from the council. We will never submit to the Empire's rule.'</p></i>",
    
    2: "<p>The memories of my meeting with the First Founder slowly faded away. When I woke up, I was being restrained.</p><p>I couldn't move my limbs or even open my eyes. My ears were ringing and my throat ached.</p>",
    
    3: "<p>'It seems you have regained your senses', a voice suddenly said. 'You are currently on the reconnaissance ship Hecate of the Sol Empire. You were abducted from your planet approximately two hours ago. As a precaution, a chip has been inserted into your body that can be used to locate you as well as to remotely terminate you.'</p><p>I had been... abducted and wired with something so dangerous? Just how did this happen to me?</p><p>'You will now meet your contact agent with the Sol Empire. Get ready.'</p><p>With that, the pressure that was keeping me locked in my position suddenly went away.</p></p>",
    
    4: "<p>I immediately opened my eyes.</p><p>It seemed like I was in a completely white room that had no decorations to speak of. Standing on both sides of the room were several human-shaped robots. Robot soldiers, looking at the weapons they were carrying.</p><p>'Sorry about the rough introduction', said a man who suddenly appeared in my view. 'My name is Michael Evans. I'll be your contact with the Empire.'</p><p>He walked to me and seemed to push some kind of a button. I could feel strength swiftly returning to my weakened limbs.</p><p>As I stood up, I tried looking around the room. It really was empty besides the guard robots and the man in front of me - Evans.</p><p>'Thank you for releasing me', I said while trying to adjust to the situation. 'My name is Paul Faron. I'm a Founder from the Teochen colony. May I ask why I was abducted?'</p>",
    
    5: "<p>Evans seemed to look at me with interest.</p><p>'You've taken this quite well', he said. 'But let's get to the main topic.'</p><p>He waved his hand and the robots backed away. Instead a large hologram full of stars and different markings appeared in the room.</p><p>'The Empire has sent scouts in every direction from Sol. We were sent here to investigate your ancient colony of Teochen.'</p><p>They considered us ancient? I almost managed to smile.</p>",
    
    6: "<p>'The artificial intelligence you just spoke to is actually in charge of this mission. I'm merely second-in-command, but I'll be the one to negotiate with you.'</p><p>It was an articial intelligence?! If so, it was very advanced compared to anything we had. It was even commanding a ship...</p><p>'Why did you want to abduct me before negotiating? Couldn't you just contact me formally?' I managed to say.</p><p>'Sorry about that again', Evans said and actually looked somewhat sorry. 'This ship is just much too expensive to put it in any sort of danger. We had to arrange the first negotiation in secret.'</p><p>Was it really a negotiation if I might die for saying something offensive? However, I kept such thoughts to myself.</p>",
    
    7: "<p>'First of all', Evans said. 'We'd like to establish a mutually beneficial relationship with you. If you agree, we won't take any action before consulting with you first. You'll also be our sole contact for the time being. This means that you'll be granted a unique position where you can greatly influence our actions. As for you, we'll only require you to keep our presence in this area a secret for now. What do you say?'</p><p>'...When you speak of actions, what do you mean exactly? What are you planning to do with our colony?'</p><p>'Ultimately, our purpose is to have your colony join the Empire's rule. I hope this can be accomplished with mutual understanding and without bloodshed.'</p>",
    
    8: "<p>It was much like I had expected. When considering our military strength and influence, it was nothing compared to the Empire. They simply had no reason to treat us as equals.</p><p>'I understand. I'll look forward to cooperating with you.'</p><p>Evans smiled at my immediate submission. From the way he acted, they probably weren't using something like mind reading technology on me. Otherwise he would have known that I was still far from having decided to serve under them. Nevertheless, there was no reason to refuse now. It would just mean being imprisoned as a hostage.</p><p>What I needed most right now was more information about the situation.</p>",
    
    9: "<p>'Then we should start our cooperation by exchanging information about your planet and our plans. Simply put, our plans are just to observe for now. We'd like to keep our own presence hidden while getting to know more about your planet. What's your opinion?'</p><p>'That sounds like the best plan', I responded with some relief. That would buy some time for myself to think about the situation as well.</p><p>But the next question crushed that brief relief.</p><p>'Before we proceed, there's something I'd like to ask. What was the 'it' that you mentioned could possibly repel us in your discussion with the First Founder?'</p><p>Suddenly I realized the reason I was abducted. They had somehow smuggled a listening device to me or the First Founder. From my discussion with the First Founder, they already knew that I had valuable information about the colony.</p><p>The most important secret of our colony immediately flashed to my mind - the large weapon that was hidden underground and that could possibly even allow us to fight back the Empire to some extent.</p>",
    
    10: "<p>It was something that not even all the Founders knew about. Our most important tool for defense. Revealing it now would be the same as selling out my colony.</p><p>'If you tell the truth, our agreement will be in effect. You'll also receive citizenship of the Empire and a generous salary as a foreign agent. If you lie, you'll be used as a hostage. It's your choice.'</p><p>Could they see through it if I lied? They probably couldn't read my thoughts, since then there would be no point in phrasing the question like that. They could simply ask for my confirmation to things they already knew.</p><p>But what would happen if I lied? Could they notice it and punish me for it? I could die any second if the artificial intelligence didn't like what I said.</p><p>If I revealed it now, it would mean committing to aid the Empire. I could no longer reveal these events to the council if I had become complicit in them. It was also true that we would only be destroyed by fighting a war against the Empire.</p><p>But... Revealing it would make it impossible to catch the Empire off guard. If they knew our full defense capabilities, they could be more aggressive with their moves. It would only make the colony's position worse.</p><p>There were too many unknown variables. All I knew is that I had to say something. My delayed answer already betrayed the fact that there was something to hide.</p><p>Should I reveal our most important secret - or just some lesser secret of ours to try and fool them?</p>",
    
    1000: "<p>'We do have a secret', I said after making my resolve. 'It's an old secret that only some Founders know about - and only the First Founder knows the full details. It's a weapon that's hidden underground and capable of destroying targets far in the surrounding space.'</p><p>Evans seemed surprised as I talked. As I thought, they had no way of reading my thoughts. It made this move all the more controversial, but I had made up my mind.</p><p>'That's useful information', Evans said. 'It's hard to say if this weapon is capable of damaging our ship, but it's good to know about the possibility.'</p><p>'I can find out more about it if I get back to the planet. Actually, I'm afraid that my disappearance might cause problems if I'm kept here any longer.'</p><p>'We've taken care of it', Evans said and started moving towards the door. 'Follow me. I'll escort you back to your residence and accompany you for information gathering purposes.'</p><p>'You? You trust me enough to put yourself on the line?' I asked while moving to follow him.</p><p>Evans laughed happily. 'You just trusted me enough to reveal your secret, didn't you? Besides, if something were to happen to me, I'm sure Hecate would be merciless towards you and your colony.'</p><p>I thought about the AI's cold attitude against me earlier and shivered slightly.</p>",
    
    1001: "<p>After that, we entered a small transport ship. It barely had enough room for the both of us.</p><p>'We abducted you while you were on your way back from talking with the First Founder', Evans told me. 'We faked your transport's signals to show that you simply took a detour. The two people who were with you are still alive, merely unconscious. '</p><p>My personal security had certainly been lacking. I'd never have expected to be attacked like that.</p><p>'They won't be a problem', I said. 'They will do whatever I say. Just take me straight to my residence and bring them along.'</p><p>Evans gave the same instructions forward. As we secretly returned to Teochen, I couldn't help thinking that not only my personal security, but the overall security of the colony was lacking.</p>",
    
    1002: "<p>After being dropped off some distance away from my residence, my two guard servants were already waiting for me - still unconscious.</p><p>Evans made a small gesture with his hand, followed by some high-pitched noise. When it ended, they both weakly rose up.</p><p>'Neither of you will talk about what happened', I said my prepared speech. 'Just treat it as me taking a walk after my meeting. My companion will be treated as a guest, but he'll be concealed with the status of a servant.'</p><p>They nodded and obediently moved behind me as I moved into the transport I had been using before my abduction. Evans joined me on the front seats while glancing cautiously at the servants.</p>",
    
    1003: "<p>The transport started to move.</p><p>'Are you sure they can be trusted?' Evans asked quietly.</p><p>'That's for certain', I answered without lowering my voice. 'Most of the people in our colony are grown artificially. They're modified to show absolute obedience towards us Founders, and above all to their assigned Founder. There has never been a case of one of them disobeying a Founder.'</p><p>Evans seemed slightly uncomfortable after hearing that. However, he didn't say anything and simply looked away as in deep thought.</p>",
    
    1004: "<p>After a while, Evans looked like he was planning to say something. That was when the transport suddenly stopped and the doors opened. I had returned home.</p><p>'Your residence is like a mansion of the historical nobles', Evans commented.</p><p>'You could consider us as a sort of nobility', I said. 'After all, our people are divided from the moment we're born.'</p><p>Evans still seemed like he had something to say.</p>",
    
    1005: "<p>'What is it?' I finally asked as we entered my residence.</p><p>Evans glanced at the various people around us. They included several kinds of servants - some were guards, some were cooks and some were couriers, for example.</p><p>'I'm just not used to slavery', he said. 'It's rare to see someone acting against their own will in the Empire.'</p><p>'It's not that they're doing anything against their own will. Their will is to serve us. Even if we wanted to, we couldn't undo what's been done to them at their birth.'</p><p>Evans didn't yet seem convinced, but he didn't pursue the issue.</p><p>As we talked, we entered my conference room. I had no worries about the loyalty of my servants, but since Evans seemed slightly uncomfortable around them, I ordered all of them to leave us.</p>",
    
    1006: "<p>Now that it was just the two of us, I brought up the most dangerous topic.</p><p>'This is the hidden weapon I talked about earlier', I said as I projected an image in front of Evans. 'It's a large laser weapon that's located underground somewhere within the First Founder's sector. It's operated by a group of his servants that never set foot aboveground. Only the First Founder knows the specifics of the weapon, and only us Founders in the council even know of its existence.'</p><p>'Do you know anything more about its exact location?' Evans asked.</p><p>'I only know that it's in the First Founder's sector. It's a rather large area, certainly the largest sector in the area that our colony has expanded to. I'll give you all the information that I have.'</p><p>After a moment of transferring data, I handed a chip containing the relevant information over to Evans.</p>",
    
    1007: "<p>'What else would you like information on?' I asked.</p><p>'I'd like to know more about this council of yours - its members, organization and authority. As well as its members' views of the Empire.'</p><p>Just as I was opening my mouth, I suddenly heard a loud alarm from my terminal.</p>",
    
    1008: "<p>I quickly looked at the reason for the alarm.</p><p>'EMERGENCY MEETING AT THE COMMAND CENTER. ARRIVE IMMEDIATELY.'</p><p>What could this be about? Why wasn't the topic even mentioned?</p><p>But it was most likely about the Empire. That was the only likely reason for the meeting to take place at our most secure base of operations.</p><p>I glanced at Evans and shut off my terminal.</p>",
    
    1009: "<p>'The Empire's presence in the area has probably been noticed', I said. 'I have to go to an emergency meeting. I don't think you should come with me, but you can stay here and contact me if necessary.'</p><p>'Could you give me access to all of your data while I'm here?'</p><p>I hesitated for a moment, but it was too late to back out at this point.</p><p>'Here you go. If you go through all this, you should know more about us than anyone besides the council.'</p><p>Now I had truly done it. If this was found out by the council, I'd be a dead man. But in truth I had already gone past that point when I revealed our greatest secret to the Empire earlier.</p>",
    
    1010: "<p>As I walked out of the mansion, I called for the head servant with my terminal. Soon enough he kneeled next to me while waiting for orders.</p><p>'Pick twelve best fighters from my servants as my personal guards and have them come with me within two minutes.'</p><p>'As you will, master', he said and moved back to the mansion.</p><p>My abduction to Hecate had shown me how lacking my personal security had been. It was unlikely that the Empire would do anything to me now, but the same couldn't be said for the other Founders if they had found out about my information leaks to the Empire.</p>",
    
    1011: "<p>No more than thirty seconds had passed until the head servant returned with twelve proficient-looking guards as promised. He kneeled again.</p><p>'I'm terribly sorry, master, but two among our best guards had been stationed elsewhere in our sector. These were the best candidates in the immediate area.'</p><p>'You've done well', I said and smiled. 'Now go and keep an eye on Evans while I'm gone. Don't interfere with anything he does, but keep track of his actions.'</p><p>'Yes, master', he said and vanished into the mansion.</p><p>He was truly a good servant. It was a shame that he didn't have even his own name, much less his own will. On the other hand, now there was no need to worry about him ever betraying me.</p>",
    
    1012: "<p>I soon arrived at the underground complex that served as our emergency headquarters after a max-speed transport.</p><p>This area belonged to the First Founder of Teochen. He had been in charge of our colony for over forty years now. It was difficult to imagine that he would step down for decades to come. I couldn't even remember what his original name had been before assuming the title of First Founder.</p><p>The security was also much tighter than I had expected. I and my own guards had to pass through several checks and tens, perhaps hundreds of guards before I was even inside the complex.</p><p>It was a good thing that I hadn't taken Evans with me. However, it'd be dangerous to be trapped here if my relationship with the Empire had leaked.</p>",
    
    1013: "<p>As I walked into the council's temporary conference room, I was greeted by various expressions. I just silently took my seat and ignored all of it.</p><p>I had left my new guard squad a short distance away and given them various instructions in case of emergencies. For the time being they were ordered to hold their position.</p><p>'Now that everyone is here', the First Founder said. 'Let's begin.'</p>",
    
    1014: "<p>'As you all know, the Sol Empire has been aggressively expanding in recent decades', he continued. 'Now we have proof that they have even reached our planet. Take a look at this footage.'</p><p>A video of a small transport ship flying in the sky played in the middle of the room. It was undeniably of the same type as the one I had used to return to the planet.</p><p>'This ship is of an unknown type for us, but it's clearly made for human use. The most likely explanation is that the Empire has started scouting our system before an invasion. Unfortunately our radars can't detect their ships, and we're currently forced to rely only on visual detection. They can deploy ground troops without our notice. However, if they try orbital bombardment, we should be able to track their location and use <i>it</i> to destroy them.'</p><p>And that's why they wouldn't recklessly shoot us from space, at least not with ships that weren't expendable. Our greatest weapon was now powerless.</p>",
    
    1015: "<p>'What should we do if they demand our surrender?' asked one of the councilors, Lafar.</p><p>'We will reject any proposals that would weaken our sovereignty. If they plan to make unreasonable demands, then we will threaten them with ordering our servants to fight to the death and to destroy everything valuable in the colony. They won't start a war with much to lose and nothing to gain.'</p><p>'What if they won't accept us not joining the Empire's rule?' I asked. 'Even if the colony is destroyed, Teochen is still a habitable planet. There should only be three of those within their areas. They'd want to use this planet for its natural resources and its easy conditions for supporting life.'</p><p>'We can also destroy the surface of the planet with <i>it</i>. And that's only the last resort. In the first place, it's meant as a threat. If we can't threaten or fight them to leave us alone, it'll be better to die with our colony than to become their servants. We Founders must always be the ones to rule.'</p>",
    
    1016: "<p>Was it truly better to be a dead ruler than a living servant? The First Founder's answer to that was obvious. I wasn't so sure myself.</p><p>'How many of you agree with this stance?' I asked cautiously.</p><p>Most of the councilors raised their hands. There were a few who didn't, but it was clearly not enough to put pressure on the First Founder.</p><p>'Our stance is decided. Faron, I already warned you. This is your last warning. Now you will either leave this meeting or you will be permanently removed from the council.'</p><p>I looked around the room, but it didn't look like anyone was willing to support me in this situation. It was a dead end.</p>",
    
    1017: "<p>'I will take a temporary leave', I said and walked out of the room.</p><p>This was hopeless. The First Founder wasn't willing to give in to the Empire, and the Empire most likely wouldn't accept a treaty that would leave Teochen as a completely independent faction.</p><p>Suddenly I heard a quiet voice from just behind me.</p><p>'I have a suggestion for you', it said.</p>",
    
    1018: "<p>I frantically turned around, but nobody was there. Three guards standing in the distance looked at me questioningly, but they didn't move or say anything. Where did that voice come from?</p><p>'This is Hecate', the voice said again. 'More precisely, this is an autonomous part of the artificial intelligence in control of Hecate. I reside inside the chip inserted into your body.'</p><p>I quickly turned around and walked to a nearby empty room.</p><p>'Can you hear me?' I whispered while covering my mouth.</p><p>'Affirmative. You can lower your voice even more.'</p><p>I locked the door and moved as far away from it as possible, then focused on the voice.</p>",
    
    1019: "<p>'It has been determined from your council meeting that a satisfying peaceful resolution will be unlikely. With your current First Founder, we cannot bring your colony to be a functional part of the Empire. At this rate only conflicts and ultimately war awaits us in the future.'</p><p>I would have argued back if I could, but I couldn't. There would be a tough road ahead of us in our relations with the Empire.</p><p>'However, currently the whole leadership of your colony is gathered here. If we were to capture them right now and force them to name you as their new First Founder, you would be able to take control over the colony and establish a peaceful relationship with the Empire.'</p>",
    
    1020: "<p>'T-that's... a drastic suggestion. Does Evans know about this?'</p><p>'No. He prefers to resolve this without violence. However, I have determined that the best long-term solution would be to have you take control of the colony. You have already proven your value to the Empire. If you agree, we can immediately raid this place and capture everyone in the council.'</p><p>I glanced nervously at the door, but there was no sign of trouble. There was still time to think about it.</p>",
    
    1021: "<p>'It seems you may require additional details. Teochen will become a protectorate of the Empire, granting full rights of passage, trade, easy access to natural resources and certain areas for stationing military systems. In return, you will gain the position of First Founder to decide all internal affairs of your colony as long as there's no great conflict with the policies of the Empire. You will be given protection against any internal or external threats, full trade rights with every system in the Empire and access to our advanced technology. The quality of life for your colony will increase dramatically, most likely making other Founders content with the situation.'</p><p>So I would become a mere puppet of the Sol Empire? Our independence would be gone, not to mention I'd be betraying all of my fellow Founders. There should be room for a better peace treaty since they clearly didn't want to start a war. No doubt would they win the war, but it would be costly for them as well.</p><p>'What about the servants?' I had to ask. 'Evans was disgusted by the idea of slavery. Would they be banned under the Empire's rule?'</p><p>'That won't be a problem for you. We can control the spread of information to avoid any major reactions about them. Even if using them became a burden, they can just be slowly phased out while we aid you in replacing them with more advanced tools.'</p><p>So this was it... My chance to become the First Founder and to easily avoid a war with the Empire. There was no guarantee that a peaceful resolution could be reached, but it could potentially be more satisfying from the colony's perspective than this violent approach.</p><p>What should I do?</p>",
    
    2000: "<p>I forced myself to temporarily imagine that there was nothing more secret than our ability to give absolute orders to our servants. If I could fool myself, there would be no difficulties in fooling them as well.</p><p>'Our greatest weapon is to order our servants to fight to the death', I told him. 'If we ordered it, they would never surrender and fight until this colony was a worthless pile of rubble. That would make even a clearly superior enemy wary of trying to attack us.'</p><p>'How is that possible?' Evans asked. 'We've noticed that there's something odd about how your society works, but...'</p><p>It seemed they hadn't yet understood how our servants functioned. Interesting. Then they couldn't have been here for long.</p><p>'It's because we're divided into Founders and servants from the moment we're born. We Founders carry the heritage of our forefathers who first arrived to this planet. The servants are grown artificially and engineered to have no survival instinct, but rather the instinct to serve us however they can. To them, our orders are absolute.'</p><p>'How do they identify Founders from other servants?'</p><p>'In most cases, it's enough if they know their assigned Founder. However, they're also taught to identify every other Founder on Teochen.'</p><p>The look on Evans' face looked briefly like disgust, but it must have been my imagination.</p>",
    
    2001: "<p>'Could I now return back to my sector?' I then asked. 'No matter how well you covered your tracks, my disappearance will soon be noticed and reported to the First Founder. Your arrival here might be revealed as they investigate.'</p><p>'I'm aware of that', Evans replied. 'You will be back soon enough, and I'll accompany you as well. Follow me.'</p><p>'You'll come to the colony personally?' I asked, surprised. 'Do you trust me that much?'</p><p>'You just revealed your secret weapon to us after all. I think it's time for me to take the next step in our cooperation.'</p><p>From the looks of it, I hadn't been found out. I might still be able to get out of their grasp.</p>",
    
    2002: "<p>We entered a small transport ship that had barely enough room for us both.</p><p>As we launched from Hecate, I couldn't help but think that they must have only put a microphone on me. They hadn't been able to read my thoughts or to see through my field of vision. I had tested the latter just now by writing two short messages on my terminal that would have been interesting to them, but not truly suspicious. There had been no reaction of any kind. Most likely they hadn't even noticed it.</p><p>Evans simply watched at the planet as we landed and seemed surprisingly relaxed. He must not have even imagined that I would be plotting something.</p>",
    
    2003: "<p>Soon we landed smoothly on the surface of my own sector. My two servant guards were still laying on the ground, motionless.</p><p>'Don't worry, they're alive', Evans said and walked towards them.</p><p>He made some sort of a gesture and I could hear a brief, high-pitched sound. My servants started to move immediately, but their movements were still very sluggish.</p><p>'Neither of you will talk about what happened', I said my prepared speech. 'Just treat it as me taking a walk after my meeting. My companion will be treated as a guest, but he'll be concealed with the status of a servant.'</p><p>They both nodded and slowly walked until they were behind me.</p>",
    
    2004: "<p>'So they won't ever disobey your orders?' Evans asked. He still seemed uneasy around them.</p><p>'No. It's physically impossible, so relax a bit.'</p><p>Even if I said that, it didn't seem like he could be completely at ease.</p>",
    
    2005: "<p>Even so, Evans swiftly entered the transport along with me and my servants.</p><p>We traveled a short amount of time in silence. Soon the transport smoothly stopped moving.</p><p>As Evans focused his gaze on my mansion, I quickly glanced at my terminal. I had already planned and started writing a message to the First Founder. There had been no reaction to that action either. This was almost definite proof that they couldn't detect what I wrote on my terminal.</p>",
    
    2006: "<p>I stepped out of the transport and looked at the view of my own mansion. Various servants were carrying out their duties and several guards were intently looking at our arrival. However, they quickly returned to their normal routines once the two guards with me passed on my instructions.</p><p>Evans seemed to be interested at the sight of my mansion.</p><p>'It's like a mansion of the historical nobles, especially with how many servants you have working under you.'</p><p>'That's not a bad comparison. Our society similarly divides people at their birth.'</p>",
    
    2007: "<p>While we walked and Evans glanced uneasily at the surrounding servants, I continued to write a message to the First Founder as stealthily as possible. Time was of the essence in this situation. Soon I'd have no choice but to reveal information about various things, and it was very possible that our greatest secret would be exposed at the same time.</p><p>As we entered the conference room in my mansion, I had luckily managed to send my message.</p><p><i>'This is an emergency. I have been captured and forced to cooperate with forces of the Empire. I have managed to avoid revealing anything crucial so far, but that will be unavoidable in the following minutes if I don't want to reveal that I'm only pretending to assist them. Call me for an emergency meeting right now and that can still be avoided.'</i></p>",
    
    2008: "<p>Not long after I had sent it, I could hear an alarm from my terminal and stopped moving into the room.</p><p>It was a message from the First Founder as I had expected.</p><p><i>'EMERGENCY MEETING AT THE COMMAND CENTER. ARRIVE IMMEDIATELY.'</i></p>",
    
    2009: "<p>'The presence of the Empire may have been noticed', I said and turned around. 'I've been called to immediately arrive at an emergency meeting. I don't think you should come with me since you could easily be revealed.'</p><p>'I understand', Evans said and didn't really look suspicious of me. 'Could you give me access to your data on the colony while you're gone?'</p><p>'Certainly. I'll order my head servant to guide you while I'm on my way. Now I must go.'</p>",
    
    2010: "<p>I rushed outside and took several of the nearest guards with me. I shouldn't be attacked by the Empire right now, but it still made me feel safer to have more security with me.</p><p>My transport was already waiting for me. As soon as I had entered it with my guards, it took off for our emergency headquarters.</p><p>I gave my head servant his instructions through the terminal. His mission would be to track Evans' actions and to erase any sensitive information before he could access it. All this was to be done in absolute secrecy.</p>",
    
    2011: "<p>It didn't take long until we had arrived at our destination. I quickly stepped outside and walked to the entrance of the underground complex. My guards followed right behind me.</p><p>Before I would meet with the First Founder again, I sent him another secret message:</p><p><i>'I've been forced to take a device that will track my location and likely also detect any voice in my surroundings. However, it's almost certain that they haven't noticed the use of my terminal. Prepare for emergency evacuation and don't let anyone say something that could compromise me.'</i></p>",
    
    2012: "<p>As soon as I had sent my message, several guards of the headquarters were already surrounding me.</p><p>'Follow us', one of them said. 'You'll receive a briefing from the First Founder before the actual meeting begins.'</p><p>I nodded absent-mindedly and followed them into the complex.</p>",
    
    2013: "<p>There were even more guards than usual in the corridors. As I walked through the endless layers of security, I slowly started to feel as if I was being freed from the Empire's grasp.</p><p>The thought was soon crushed when I remembered that they could kill me remotely whenever they wanted.</p><p>With various concerns on my mind, I entered the emergency meeting room. I left my own guards behind the door.</p>",
    
    2014: "<p>The room was filled with seats for the whole council, but currently they were all empty except for one. The First Founder was sitting in his own seat and intently looking at me. He was flanked by his personal guards on both sides.</p><p>'There's been a sighting of the Empire', he started. 'A servant saw an unidentified transport ship hovering towards the ground from a distance. What's more, it was going towards your sector. Before we start the meeting, do you have something to say that could give us more information about the situation? Have your own servants noticed anything?'</p><p>Was this a real sighting? No, it didn't matter. I just had to deny it.</p>",
    
    2015: "<p>'I haven't noticed anything out of the ordinary.'</p><p>'Is that so? Then this sighting must have been very lucky. However, it's certainly not a false alarm. We haven't been able to detect anything with our radars, but take a look at this.'</p><p>A video of a transport ship flying in the air was projected in front of me. It was of the same type as the ship that I had used to return to Teochen, or perhaps even the exact same ship.</p>",
    
    2016: "<p>'It's surely not one of our own ships, which means that the Empire's presence is the best explanation.'</p><p>The First Founder nodded and terminated the video.</p><p>'Order your own servants to be as alert as possible and have them prepare for battle. We don't know what they want or how large a force they have here, but if their purpose was something beneficial for us, they would have already contacted us.'</p><p>That was certainly a good point. Had they even told me the complete truth yet? It was most likely not a lie that they ultimately wanted to annex Teochen, but they might have other immediate plans that I didn't even know about.</p>",
    
    2017: "<p>'One more thing. You should stay here until the meeting starts, since they might have infiltrated your sector in order to assassinate or capture you. Even if they followed you here, this is the most secure location on the planet. It's better to be cautious at times like these.'</p><p>'Very well.'</p><p>Our act had probably succeeded by now. By publicly denying that I knew anything about the Empire, their potential suspicions of me would be reduced. By staying separated from Evans, there would be fewer chances of me being exposed.</p><p>'I have another issue to attend to, but the meeting will start shortly. Until then.'</p><p>With that, I was left alone in the conference room. But the real discussion was just about to start.</p>",
    
    2018: "<p>Under the pretense of ordering my servants to be more alert, I immediately started operating my terminal. In truth, I used it to send another message to the First Founder.</p><p><i>'A chip has been inserted into my body that can be used to remotely kill me. If our plan for the Empire involves my role being exposed, we'll need to disable it one way or another. However, I think it would be useful to keep up the act for now. In addition, it's not certain if it could be disabled without killing me in the process, so I'd rather not take unnecessary risks.'</i></p><p>After a short while, I received a reply.</p><p><i>'An electromagnetic pulse will most likely disable such a device without triggering it to kill you. I will arrange for a weapon that can be used to target you before we take any action. Do you have some way to directly contact the Empire?'</i></p>",
    
    2019: "<p>I tilted my head as I wondered what the last sentence meant. Did the First Founder want to personally negotiate with the Empire now?</p><p><i>'Yes, I can contact the second-in-command of the spaceship orbiting Teochen. Why?'</i></p><p><i>'How many ships do they have in our system?'</i></p><p><i>'As far as I know, only one.'</i></p><p>The next reply took longer to arrive, but when I saw it, I was shocked.</p>",
    
    2020: "<p><i>'Then now is our chance to show our will and ability to defend ourselves to the Empire. With your cooperation, we should be able to destroy that ship of theirs. We only need to taunt them in our meeting by doubting their superior military, and afterwards you will suggest them to show the destructive power of their ship by bombarding our planet. At that moment, we should be able to detect their ship and aim </i>it<i> at them. We should be able to deal a decisive blow with a surprise attack of our greatest weapon. After they've seen that we're not simply a backwards colony to be conquered, they'll have to assume that we might have other hidden weapons as well. In addition, we could salvage the wreck of their ship to discover some of their secrets. After the years it would take for more of their forces to arrive here, we would be in a much better position to negotiate with them.'</i></p><p>Was the First Founder planning to start a war with the Empire?! I quickly sent a response.</p><p><i>'There's no guarantee that we would succeed in destroying Hecate or that there aren't more of their forces nearby. Are you sure it's wise to gamble the survival of our colony on the possibility of improving our future position? They might as well feel that they'll need to punish us or the ones responsible for this decision.'</i></p><p>This time his answer came without delay.</p><p><i>'Our servants will fight them to the death if need be. In the worst case, we could even make this planet uninhabitable. But I don't think it would go that far. If I was in their position, I would show far more consideration to an opponent who can defend their own territory instead of just bowing to their demands.'</i></p><p>He wasn't completely wrong. This would show them that we were willing to risk annihilation to defend our rights. If we were too eager to achieve peace, they might take it as an opportunity to demand even more from us. Even so, we <i>would</i> be annihilated in a war against the Empire. It was a grave risk to take.</p><p>It was also too late for me to go to the Empire's side. I had already lied to them and revealed everything to the First Founder. It would soon be inevitable to attempt removing the chip they had forced on me. Even if there was a chance that I would die while trying to disable it, my death would be almost certain if the Empire realized what I had done so far.</p><p>Should I go along with the First Founder's plan or refuse to cooperate?</p>",
    
    3000: "<p>'I'll agree to it', I finally answered. 'That's the best way to solve this without risking a war.'</p><p>'Very good', the quiet voice of Hecate whispered back. 'Now move back to the other councilors so that I can track their location and quickly arrive there. I will use minimal force in capturing the councilors themselves, so there's no danger of you being harmed.'</p><p>'Understood.'</p><p>I walked back to the door and cautiously opened it. However, the same guards were still standing in the distance without showing any clear signs of suspicion.</p>",
    
    3001: "<p>After returning to the conference room, I whispered very quietly 'Go' and sat down on my seat.</p><p>'Someone sent a transmission to the outside!' a servant behind the First Founder shouted.</p><p>Immediately the terminals around us started to flash with a red light and a loud alarm sound started to ring. Everyone except the First Founder looked dumbfounded.</p><p>'I figured they might try something like this', he said. 'This is a deathtrap for them if they want to attack us. Most of my servants are also stationed a short distance away from here.'</p><p>Suddenly he looked at me with suspicion.</p><p>'A transmission was sent from here and immediately the Empire attacked us? Arrest Faron! He's not only a coward, but a traitor as well!'</p>",
    
    3002: "<p>I hadn't expected that the First Founder would immediately realize I was a traitor, but I still quickly took cover behind my council seat. Several stun bolts shot by the five guards behind the First Founder barely missed me. The other councilors still seemed shocked at what was happening and hadn't even moved from their seats.</p><p>I quickly pressed my terminal to the send one of the instructions to the guards I took with me:</p><p><i>Rush to my location as quickly as possible. Kill the servants and restrain the Founders.</i></p>",
    
    3003: "<p>'Catch him quickly! We're losing control of the upper floors and need to evacuate. Everyone else, get to the emergency exit!'</p><p>The First Founder's servants started to move towards me. At the same time, the other councilors started to rise up from their seats. It looked like my time was running out.</p><p>But just as his servants were about to reach me, I heard several weapon shots outside the room. Luckily it seemed like the Empire had distracted the First Founder enough that he had forgotten about my personal guards.</p>",
    
    3004: "<p>The other councilors turned towards the door, surprised, when it was suddenly blasted open by my servants.</p><p>'Forget about Faron! Kill them!'</p><p>The First Founder's words were too late. His servants were slow to react to the sudden event, since they were still following the previous orders of approaching me. They barely managed to turn around as they were gunned down by my own servants.</p>",
    
    3005: "<p>'Restrain them without making them lose consciousness', I said to my servants.</p><p>'Damn you, Faron!' the First Founder shouted. 'Don't you have any dignity left? If you do this, our glorious past will be nothing but a distant memory. Let us leave now and I'll reduce your punishment to simply being exiled.'</p><p>As he finished saying that, he was forced to lower his head. My servants had caught all the Founders and made them face the floor in front of me.</p><p>Could I still revert my decision? No. Then I'd become an enemy to both sides of the conflict.</p><p>'I have already made my decision. With you as the First Founder, only ruin awaits us. Even if I have to sacrifice our independence, I'll make sure to safeguard our colony under the Empire's rule.'</p>",
    
    3006: "<p>Soon after I had managed to capture the council, several insect-like robots flew into the room. After looking at the situation, they simply retreated back outside.</p><p>Following them, tens of human-sized robots wielding various weapons entered the room. Most were filled with scratches or even broken parts, but none of them seemed seriously damaged.</p><p>'We now control most of this facility', one of them said. It must have been Hecate behind the voice. 'The battle aboveground is still taking place. We will surely defeat the enemy, but it would be for the best to surrender now and minimize losses on both sides.'</p><p>'Never!' the First Founder said furiously. 'We'll never give in to your demands. Even if I'm to die here, you won't get our planet so easily. Our servants have been instructed to fight to the death if we disappear - '</p><p>Suddenly I could hear a high-pitched sound and the First Founder collapsed to the ground.</p>",
    
    3007: "<p>'You are no longer needed', Hecate said. 'Now, councilors. It's time to decide. Either you will all die here and we will decimate your servants in a prolonged ground battle, or you will instruct your servants to stand down and name Faron as your new First Founder. You have thirty seconds.'</p><p>I looked worriedly at the other councilors. Would they be able to make the correct choice on such a short notice?</p><p>But perhaps it was <i>because</i> of the time limit that most of them soon agreed. It seemed like they had realized that further resistance was meaningless.</p><p>Needless to say, the ones who didn't agree were stunned and dragged off along with the First Founder.</p>",
    
    3008: "<p>Normally the First Founder would have named his own successor, but I'd never be chosen that way. In this situation, our only choice was an emergency decision by the council.</p><p>'Now order your servants to cease fighting and clearly declare your will to choose me as the next First Founder', I said to the councilors.</p>",
    
    3009: "<p>Every remaining councilor started operating their terminals. I glanced at Hecate's robots next to me as the most powerful rights of the colony transferred to me.</p><p>'This is sufficient', Hecate said. 'Now, First Founder, order your anti-spaceship weapon disabled. I will bombard the sectors of those Founders who refused to obey.'</p><p>The other councilors seemed shocked, and I'd be lying if I wasn't slightly shocked as well. However, I could understand the reason. It would be wasteful to fight a ground battle against all the servants who would still fight to the death.</p>",
    
    3010: "<p>'It's done', I said to Hecate.</p><p>'Most of the resisting servants will be dead soon', one of the robots said and turned to the other councilors. 'The coup has succeeded. With Faron as your new First Founder, every remaining councilor will keep their position. As long as you pledge to support him, there will be no further violence between us.'</p>",
    
    3011: "<p>There was no resistance to be seen on the faces of the councilors. After witnessing the Empire's swift dismantling of our defenses, and getting to keep their privileged positions after all this, they should have no reason to rebel. They had already chosen the path of submission by naming me as the new First Founder.</p><p>The way to survive in this world was not safeguarding your principles to the very end. It was to adapt and to choose the best answer for each situation.</p><p>We had retained a relatively autonomous position. By conceding some of our rights to the Empire, we would be able to reap other benefits. Perhaps it was the start of great progress rather than oppression.</p><p>Everything was in my hands now.</p><p>A SERVANT AND A RULER - END</p>",
    
    3012: "<h1>Story and Development</h1><br><p>Teemu Salminen</p><h1>Music</h1><br><p>Yousif Abdullah</p><p>rubberduck</p><p>cynicmusic</p><p>yd</p><p>Nikke</p>",
    
    4000: "<p>'We can still reach an agreement', I finally decided. 'I'll contact Evans and see what I can do. Thanks for your suggestion, but I don't want to start a battle unless it's absolutely necessary.'</p><p>'Very well', Hecate said. 'I will monitor your progress and take action if needed.'</p><p>With that, Hecate's voice vanished.</p>",
    
    4001: "<p>Instead of returning to the council, I walked all the way to the upper floors and back to the surface of Teochen. I was followed by my personal guard squad.</p><p>Once there, I immediately contacted Evans.</p><p>'How did the meeting go?' Evans asked before I could say anything.</p><p>'Not well at all. The First Founder is stubbornly refusing the Empire's influence on us and planning to even self-destruct the whole planet if he needs to. The situation is almost hopeless, but I think there could still be a chance for a peaceful agreement.'</p>",
    
    4002: "<p>After listening to my explanations of the situation, Evans still seemed surprisingly optimistic.</p><p>'I'd like to meet this First Founder of yours now. I have some ideas for how this could still work out. Give me a transport to where you are now and I'll be there as soon as possible.'</p><p>'Will you really be coming here yourself? What if the First Founder takes you as a hostage?'</p><p>It was far from impossible, especially considering that it would give him more power to threaten the Empire with.</p><p>'I'm willing to take that risk. If that were to happen, it would start a war with the Empire and my own life wouldn't count for much in that situation.'</p>",
    
    4003: "<p>'If you say so...' I reluctantly agreed.</p><p>It was still hard to be sure if that would convince the First Founder, but he should at least listen to what Evans had to say.</p><p>Doing this also meant that I would be exposed as a collaborator with the Empire, but now was too late to worry about that. If the First Founder decided to attack us in our meeting, it would mean war and the deaths of everyone on this planet regardless.</p><p>I made a couple of commands on my terminal. With this, Evans should be here soon.</p>",
    
    4004: "<p>I waited for a few minutes, and Evans arrived on one of my own transports just in time.</p><p>'This base seems well made', he commented. 'It could even withstand orbital bombardment for some time.'</p><p>'Its main purpose is to be hard to detect from space. No amount of metal will help against several direct hits.'</p><p>Evans smiled.</p><p>'Hopefully there will be no need for bombardment. If we fail in our negotiations, we will both die along with your council.'</p>",
    
    4005: "<p>As I entered the base with Evans and my servants, we were soon stopped at one of the checkpoints.</p><p>'You're not a registered servant', one of the guards said to Evans. 'Nor are you a Founder. Who are you?'</p><p>'He's with me', I said. 'Contact the First Founder for me. I have important news for him.'</p><p>He didn't hesitate to contact the First Founder. As expected, the servants avoided making independent decisions whenever possible.</p><p>'What's this about?' the First Founder asked. 'You were already removed from the meeting. Or did you change your mind about our stance towards the Empire?'</p><p>'It's a different issue. I have brought someone from the Empire with me, ready to negotiate an agreement with you.'</p>",
    
    4006: "<p>'Are you a fool?! Why did you expose our headquarter's location to them? No... They must have bribed you. That would explain your actions so far.'</p><p>'That's not it. A war with the Empire would be the same as committing suicide. But now that you have a chance to avoid a war, won't you take it?'</p><p>The First Founder was silent for a while. Then he seemed to have made his decision.</p><p>'I will meet with him. However, you will both be throughoutly searched and your servants will be disarmed. Is that fine with you?'</p><p>'That's fine. If you attempted to harm us, it would lead to a war with the Empire, and our goal is to stop that from happening.'</p><p>'Faron has been granted diplomatic immunity as well', Evans added. 'If something were to happen to him, it would be the same as attacking a diplomat of the Empire.'</p><p>'You... I understand. As long as we're at peace with the Empire, I will guarantee safety for the both of you.'</p>",
    
    4007: "<p>As we arrived back at the council's conference room, I noticed that the First Founder was waiting for us alone. There were just a couple of his own guards standing watch at the door.</p><p>'I had the others leave back to their sectors for now', he said. 'This will be between me and the Empire.'</p><p>That made sense. The majority of the council supported the First Founder above all. Not only that, but even some of the more pro-peace councilors might be comforted by the knowledge that the First Founder would never accept an unreasonable deal. Perhaps some part of me appreciated that as well.</p>",
    
    4008: "<p>'My name is Michael Evans, and I have the authority to negotiate on behalf of the Empire. It's a pleasure to meet you.'</p><p>The First Founder looked at Evans with some suspicion.</p><p>'Do you have some way to prove your position?'</p><p>Evans projected an image in front of him. It was a very detailed picture filled with his personal information, including titles such as 'Ambassador' and 'Intelligence officer'.</p><p>'If you still have doubts, I can order our army to show some kind of performance to you.'</p>",
    
    4009: "<p>'No, it's enough', the First Founder said. 'In the first place, it's clear that you're from the Empire. I am the First Founder of our colony. What's your proposal?'</p><p>'Our most important demand is that Teochen will formally become part of the Empire, granting citizens of the Empire free passage and trade through this system. However, when I say formally, I truly mean it. It's not a big problem if Teochen will remain autonomous in its internal affairs and demilitarized of our fleets. It would also be crucial to build infrastructure for supplying spaceships to further explore the space around us.'</p><p>'Isn't that contradictory? When you say that we would remain autonomous, doesn't it mean that we would retain the right to choose who we allow in and who we trade with?'</p><p>'Autonomy isn't something that gives you unlimited rights. You have to consider that our fleets could smash your colony like it was an insect crawling on the ground. We can't afford to lose face in front of our citizens. If it seemed like your colony was the only one to benefit from formally joining the Empire, it would make people question why we didn't just take everything by force. This way both of us will benefit and we avoid an unnecessary war. Isn't that the best solution?'</p>",
    
    4010: "<p>The First Founder leaned back in his seat.</p><p>'I trust you've heard from Faron what we could do if we were pushed too far into a corner. It's not wise to threaten us like that.'</p><p>'I'm merely stating the facts. We now know everything about your colony, and we could subjugate this planet even without calling for reinforcements. I hope you can take a good deal when you see one, because I'm afraid this is the most I can do to avoid the immediate destruction of your rule.'</p><p>The First Founder briefly glared at me. I tried not to change my expression. It was true that I had leaked our secrets, but if that caused him to waver in his stance, then it had already been worth it.</p>",
    
    4011: "<p>'Fine', he said at last. 'I can agree to a formal declaration of joining the Empire's rule. But we will fight for our autonomy to the end. No Empire military will be allowed to the system, and we'll have to discuss further details about your demands for passage and trade. It cannot be unlimited or we would lose our position as the ruling class.'</p><p>Suddenly he turned to look at me.</p><p>'Lastly, Faron will be exiled from Teochen. If you've granted him diplomatic immunity, you can surely grant him asylum as well. I can't have your agent ruling over a large sector of my colony. In addition, you will turn over your servants to other Founders before leaving.'</p>",
    
    4012: "<p>Evans glanced at me and I nodded. I had expected to leave Teochen regardless. It wouldn't be safe for me to remain here after all I had done to betray the council.</p><p>'It's tentatively agreed, then. I'll contact my superiors for further details, but this should be an acceptable result for the time being. I hope we can continue to work together in peace.'</p><p>'That depends on you as well.'</p><p>The First Founder looked surprisingly satisfied with the situation. He turned away from us and seemed to be thinking about something.</p>",
    
    4013: "<p>'You are free to leave as you please. I have to meet with the other councilors now.'</p><p>We both rose up to leave.</p><p>'We will temporarily leave this system, but make sure to prepare for formally joining the Empire. Someone higher-ranking than me will arrive in the near future to finalize our agreement.'</p><p>'I will... Good travels for the both of you.'</p>",
    
    4014: "<p>We encountered no resistance while we walked to the upper floors and reached the outside.</p><p>My transport and my servants were already waiting for me. I briefly looked back at the entrance to the underground complex, but then turned to face Evans.</p><p>'That went much better than I expected. I assume I'm a citizen of the Empire now?'</p><p>'Yes, I have the authority to grant you citizenship. There should be no trouble with your status after all the services you've given us.'</p><p>I smiled slightly. No doubt would I be remembered as a traitor in Teochen, but it would be very different from the Empire's perspective. And ultimately history would be written by the Empire, not by our small-minded council of Founders.</p>",
    
    4015: "<p>We briefly returned to my mansion to retrieve some valuable items and to order my servants to be redistributed among the other Founders, but soon left my sector for good.</p><p>We flew back to Hecate on the same transport ship we had used before. The large reconnaissance ship was still stationed on close orbit around Teochen.</p><p>I was now back to where it had all started. I had switched sides and lost my status as a Founder, but our colony was still an autonomous entity and I had gained the favor of the Empire. The situation wasn't so bad.</p>",
    
    4016: "<p>As Hecate departed from the orbit of Teochen, I looked back at my colony with mixed feelings.</p><p>'Do you miss it already?'</p><p>'Hardly. There's no place left for me there.'</p><p>I turned away from Teochen and looked at the stars around us. Evans fell silent as well.</p><p>Immediate outbreak of war was avoided, but there was something odd about the ease of the First Founder's submission. Depending on his actions, the colony could still face war in the future.</p><p>However, the fate of the colony no longer concerned me. I belonged to the Empire now.</p><p>EXILED - END</p>",
    
    4017: "<h1>Story and Development</h1><br><p>Teemu Salminen</p><h1>Music</h1><br><p>Yousif Abdullah</p><p>rubberduck</p><p>cynicmusic</p><p>yd</p><p>Nikke</p>",
    
    5000: "<p><i>'I understand. Let's proceed according to your plan.'</i></p><p>This might cause the destruction of our entire colony, but it was the best way to protect our sovereignty. The First Founder was right. We couldn't bow down so easily. Perhaps the Empire would take us more seriously after we had shown them our strength.</p><p><i>'The other councilors have been waiting nearby. The meeting will begin shortly.'</i></p><p>I looked at the door to the conference room, and soon the First Founder entered the room along with his guards and the other councilors.</p>",
    
    5001: "<p>Each councilor took their respective seats.</p><p>'This is an important moment for our colony', the First Founder said. 'We have obtained proof that the Empire has infiltrated our planet. Take a look at this footage.'</p><p>He projected the same video he had shown me earlier for everyone to see. It was undeniable that it wasn't our own ship, and the probability of it not being from the Empire was non-existent.</p>",
    
    5002: "<p>'They have managed to infiltrate our territory so far, but we won't allow it to continue. From now on, I ask everyone to stay on high alert and report any new sightings directly to me. In addition, all capable servants should be armed and prepared for battle. We can't allow these pesky intruders to bother our colony any longer.'</p><p>The council was full of approval to the First Founder's speech. However, there was an unnatural tension among the councilors. It must have been because they knew that this meeting was merely a farce to fool the Empire.</p><p>Soon enough the meeting concluded and the councilors departed from the room. I rushed to a nearby empty room to contact Evans as planned.</p>",
    
    5003: "<p>After checking that I was alone, I quickly contacted Evans.</p><p>'The situation is bad. The First Founder thinks that we can easily take care of the Empire. They're utterly ignorant of your military strength.'</p><p>'How can they be so ignorant? They should have been able to realize the vastness of our resources at least to some extent.'</p><p>'They may be just refusing to accept reality. Perhaps you should demonstrate your military might in some form - for example by bombarding areas close to the colony from space? That should work as a warning.'</p>",
    
    5004: "<p>The connection was silent for a while.</p><p>'That's not a bad idea. We will hit uninhabited areas around the colony as a warning. I suggest holding onto something while we do it.'</p><p>'Good. I'll contact you again afterwards.'</p><p>After the connection had closed, I instructed my servants to capture Evans and bring him back to our headquarters when they could confirm that the bombardment had started.</p><p>Only a moment had passed until I could feel the earth around me starting to tremble.</p>",
    
    5005: "<p>As soon as I could feel it, the door in front of me opened. A servant carrying a large weapon was standing behind it. It must have been the electromagnetic pulse that the First Founder was talking about.</p><p>While he aimed the weapon at me, I detached the terminal from my hand and threw it across the room. I didn't want to break it along with the chip, after all. Without wasting any time, the servant launched his weapon at me.</p>",
    
    5006: "<p>I could feel some electricity coursing through me, and suddenly I felt a strong pain in my back. I dropped to my knees and gasped for a moment. My vision blurred for a moment.</p><p>After the pain had passed, I slowly stood up.</p><p>The bombardment had stopped and our weapon had been launched. I was still alive. Now only one question remained - had we succeeded?</p>",
    
    5007: "<p>I took the terminal from the ground only to see that I had received a new message from the First Founder.</p><p><i>'The attack was successful. We managed to hit their ship directly and it's currently only a wreck unable to even move. I have already sent ships to salvage whatever we can from it.'</i></p><p>It took me a moment to truly realize that we had won.</p>",
    
    5008: "<p>I returned to the conference room escorted by several medical servants. Apparently my body was still fine even after the electromagnetic pulse.</p><p>Two people were waiting for me there - Evans and the First Founder.</p>",
    
    5009: "<p>'I'm disappointed that you chose to do this', Evans said and looked away. 'It would have been better for everyone involved to settle this peacefully. It won't take long for the nearest fleet to arrive here, and I wouldn't be surprised if they simply annihilated your colony without even considering a negotiation anymore. If you want to live, I suggest offering unconditional surrender and executing the ones responsible for this.'</p><p>'That won't be happening', the First Founder said. 'We might not be able to win in a straightforward battle, but we can cause them endless difficulties with our servants if they try to occupy Teochen. If that's not enough, we can self-destruct along with the planet. They will either come around to see our point of view or regret not doing so.'</p><p>Evans turned to look at me.</p><p>'How did you agree with this? You should understand that there's no way you'll succeed with this plan. We have thousands of spaceships, each one of them capable of destroying your colony.'</p>",
    
    5010: "<p>'Let me ask you instead', I said and turned to face Evans. 'If an alien civilization approached the Sol Empire and ordered you to become their vassals, would you comply without a fight?'</p><p>Evans slightly averted his gaze. I already knew his answer.</p><p>'Even if we're inferior to you, and even if we might die because of this, we still have our history and pride. We can't abandon our own past so easily.'</p><p>'My opinion of you has improved considerably', the First Founder commented. 'Based on your services to our colony today, you have moved to the first spot in my choices for the next First Founder. I will also appoint you with the task of stopping the Empire's return to our system.'</p><p>'I am honored.'</p>",
    
    5011: "<p>This was a heavy responsibility, but it was mine to bear. It had been my choice that our relationship with the Empire had reached this dangerous stage.</p><p>Even if I didn't originally think so, I had become able to understand the First Founder's point of view. Survival wasn't all that mattered. If we gave up everything to achieve peace, what worth was there in being able to live on?</p><p>I briefly glanced towards the stars. I could imagine several fleets of the Empire already approaching us. Perhaps this was our final stand, but at least we had remained as ourselves - Founders of Teochen.</p><p>RELENTLESS - END</p>",
    
    5012: "<h1>Story and Development</h1><br><p>Teemu Salminen</p><h1>Music</h1><br><p>Yousif Abdullah</p><p>rubberduck</p><p>cynicmusic</p><p>yd</p><p>Nikke</p>",
    
    6000: "<p>I couldn't do it. There was no guarantee that Hecate would be destroyed in the attack, and there might be other ships nearby. Even if we succeeded with the first stage of this plan, there was a high chance that it would trigger a war that would cause our destruction.</p><p><i>'I have a better idea. We can show our will to defend ourselves by simply emphasizing that our servants will inevitably fight to the death if we're attacked. I also have a high-ranking officer of theirs in my custody. If we take him as a hostage, we can again show that we have the will to fight them if necessary. However, we can ultimately release him to ease the tensions between us - while if we made a clear attack against them, there would be no way to improve our relations afterwards. It could even just increase their motivation to attack us since they'd have an easy justification to do so.'</i></p><p>What followed was a long silence. It might have meant that the First Founder was either undecided or thinking of ways to convince me.</p>",
    
    6001: "<p>At last he answered.</p><p><i>'I can understand your argument, but doing that will make it impossible to easily defeat this ship if it comes down to a fight. In that case, your eagerness for peace will be the cause of much bloodshed. If we choose to do this and a battle starts regardless, you will be stripped of your status and servants. In addition, you'll be responsible for all of our losses. Are you still willing to do it?'</i></p><p>I could feel myself slightly shivering at the thought of that scenario. Not only would our colony be in ruins, but I would personally lose everything.</p><p>What should I do...?</p>",
    
    7000: "<p>Was my personal risk truly that important? This choice would decide the fates of everyone in the colony, including me.</p><p><i>'I still stand by my decision. Even if we can't as easily defeat Hecate after they realize I've betrayed them, we should take the path that will most likely lead to our survival. If we fight the Empire, the result will only be our destruction.'</i></p><p><i>'Very well. If you're so certain that we can reach a satisfying result by negotiating with them, I will agree to it. Prepare your servants to bring this officer back here as swiftly as they can. First we must attempt to disable the chip they put on you. If you die in the process, I promise to arrange the negotiation regardless.'</i></p><p><i>'Understood.'</i></p>",
    
    7001: "<p>I operated my terminal for a while to instruct my servants on how to handle Evans. It seemed that he was still studying my databases, but the head servant had managed to prevent any sensitive information from leaking to him.</p><p>As soon as I finished, I noticed a servant carrying a large weapon entering the room. It must have been the weapon that would cause an elegtromagnetic pulse.</p><p>While he aimed the weapon at me, I detached the terminal from my hand and threw it across the room. I didn't want to break it along with the chip, after all.</p>",
    
    7002: "<p>When my terminal had flown behind the servant, he launched the weapon at me. I could feel a slight shock throughout my body, along with a sudden pain in my back.</p><p>I gasped and dropped down to my knees. I could hear several servants rushing into the room, but my sight was becoming more hazy.</p>",
    
    7003: "<p>Just as I thought I was going to die from the pain, it started to go away. My vision became clearer as well.</p><p>I was surrounded by medical and guard servants. However, my pain had already all but disappeared. I immediately took the terminal and sent the order to my own servants to capture and bring Evans back to our headquarters.</p><p>'Quickly check that there's no danger to my health', I ordered the surrounding servants. 'But make it quick. Time is of the essence right now.'</p>",
    
    7004: "<p>The servants rushed into action and checked my body with various devices. In the end, it didn't seem like my health was compromised in any way. Even the chip appeared to be completely inactive now.</p><p>Just then I received another message from the First Founder.</p><p><i>'We will now begin a private meeting with the hostage from the Empire. It will only be you, me and him. I will arrive as soon as I've secured the hostage.'</i></p>",
    
    7005: "<p>I waited a while until the First Founder, his guards and Evans walked into the conference room. The hands of Evans had been chained together behind his back.</p><p>The First Founder sat on his own council seat. Evans was forced to sit on one of the council seats between me and the First Founder.</p><p>'Greetings, Michael Evans of the Empire', the First Founder said. 'As you can see, your plan to infiltrate our council has failed. You are now our prisoner unless we can reach a satisfying agreement which includes your release.'</p>",
    
    7006: "<p>Evans glanced at me with some regret in his eyes. Then he turned his attention to the First Founder.</p><p>'The Empire won't hold my life in such a high value. You'd be better off trying to appease our military leadership rather than threatening them with a hostage. You should know that many of them have been hoping for a chance to gain true military achievements. With the convenient excuse of my capture, they would push for a chance to leave their names in history as the conquerors of this planet. You should release me immediately and maybe we can still reach a peaceful agreement. That's my only wish... I joined the military in order to avoid our power being used for meaningless slaughter.'</p><p>The First Founder's eyes met mine. He was clearly annoyed. At Evans or me for suggesting this method? Perhaps it was both.</p><p>'If it comes to a war, we won't go down without making you pay for every inch of our territory. As you know, our servants will never surrender. We can even turn the whole planet into an uninhabitable wasteland. Would you truly want to fight a war where we would both lose? If only you would treat us as equals, none of this would be an issue.'</p>",
    
    7007: "<p>Evans smiled and apparently stopped himself from laughing.</p><p>'No matter what you compare, the Sol Empire and this colony aren't equals. Our fleets have thousands of spaceships. We have countless self-replicating drones that are spreading throughout the galaxy. We're prepared to rule over the whole galaxy and all life that may exist within it. That also includes your colony. If you were to formally join our rule, you could retain autonomy in your internal affairs and gain many benefits from being part of the Empire. If you uselessly cling to your pride, it will only mean your swift destruction.'</p><p>The First Founder rose from his seat.</p><p>'We will not join the Empire! Is there no way of achieving peace without our submission?'</p>",
    
    7008: "<p>'I'm afraid not', Evans said. 'I'm sure Hecate will retreat in this uncertain situation, but it won't be long before our fleets will arrive to this system. If you're still stubborn about refusing to join the Empire, your end will come swiftly and decisively. I hope that you'll be able to finally make the correct choice when that time comes.'</p><p>The First Founder's expression was both furious and anxious. I chose this moment to interrupt the discussion.</p><p>'Would a purely formal declaration to join the Empire's rule be enough? Even if we truly retained full autonomy, it would allow both sides to keep up appearances. The Empire's leadership would be able to claim that they had gained our submission without even having to fight, and our colony would still be able to continue our legacy of self-rule. We would merely accomodate the Empire in some issues that they see as absolutely necessary, while the Empire would accomodate us with their trade and technology as compensation.'</p>",
    
    7009: "<p>Both Evans and the First Founder looked at me intently as I talked. However, the First Founder soon turned his gaze away.</p><p>'That's still not acceptable. We can't spit on the memories of our ancestors so easily by naming the Empire as our rulers.'</p><p>'Isn't it more shameful to utterly destroy their legacy by getting ourselves destroyed when we have the option to survive simply by swallowing a bit of our pride?'</p><p>'It's not that simple. If we formally abandon our sovereignty, do you really think they will be content with that? They will make more and more demands to reduce our autonomy. Each new demand will be harder to resist after we've already given up some of our rights. In the end, there will be nothing left of us.'</p>",
    
    7010: "<p>Evans had listened closely to our argument.</p><p>'Even if that happened, would it be such a bad way for things to proceed? Teochen could slowly integrate with the Empire, rather than being destroyed or immediately converted. It would be a considerably smooth approach compared to the other options.'</p><p>'You wouldn't understand. Our pride and status are all we have. If you take those away, we have nothing. My legacy won't be about abandoning our sovereignty and bowing to foreign powers. Teochen will remain independent, and the Empire will acknowledge that or pay a heavy price for forcing us to fight for our rights.'</p>",
    
    7011: "<p>Had it all gone to waste? I didn't think remaining autonomous and slowly integrating with the Empire was a bad future. There would be no risk of war, and we Founders might even improve our positions in some ways. Even so, our positions would probably be described as servants of the Empire in history.</p><p>Before I could say anything, the First Founder turned away from us.</p><p>'Imprison the hostage with maximum security and raise the alert status of the whole colony to the maximum. Every Founder is to order their servants to arm themselves and prepare for war. All of our radars are to be closely examined for signs of this ship that is hiding in our system. Available ships will be launched into space to search for it as well.'</p>",
    
    7012: "<p>After the First Founder had given his orders, his servants swiftly surrounded Evans and dragged him out of the room. Then the First Founder turned to face me.</p><p>'As for you, Faron, you'll come to regret that you didn't help with destroying their ship. I'll make sure that your status and servants are stripped away from you. For now, you'll be imprisoned along with the hostage.'</p><p>'Wait! Didn't you say that would only happen if a fight started? That still hasn't happened!'</p><p>'That's irrelevant. We lost our momentum because of this mistake, and it's all because of you. Take him away. And restrain the guards he took with him. We'll want them alive if we need to fight the Empire.'</p>",
    
    7013: "<p>Before I could do anything else, the First Founder's servants surrounded me and chained my hands together behind my back. I was powerless to resist. At the same time, I could hear stun bolts being shot in the distance. My guards must have been taken by surprise.</p><p>Was this truly the end? Was there nothing more I could do? Everything I had achieved so far was gone, and the colony would likely be destroyed in the near future. I couldn't even count on being helped by the Empire after I had just gravely betrayed them. This was such a miserable fate.</p><p>As I was being escorted through the corridors by tens of servants, I glanced towards the stars. Had Hecate already left the orbit of Teochen or was it still observing the situation? Regardless of that, the Empire's fleets would soon be approaching as well.</p><p>It was hard to imagine how we could survive through this adversity.</p><p>POWERLESS - END</p>",
    
    7014: "<h1>Story and Development</h1><br><p>Teemu Salminen</p><h1>Music</h1><br><p>Yousif Abdullah</p><p>rubberduck</p><p>cynicmusic</p><p>yd</p><p>Nikke</p>",
    
};